version: '2'

services:

  cppgreet:
    image: cppgreet-svc

  pygreet:
    image: pygreet-svc
    command:
      - run
      - pygreet_api.yaml
      - "-v"
    ports:
    - "3000:5000"
    environment:
      CPPGREETER: "cppgreet:50051"
    links:
    - cppgreet
