version: '2'

services:

  cppgreet:
    image: cppgreet-svc

  pygreet:
    image: pygreet-svc
    ports:
    - "5445:5000"
    environment:
      CPPGREETER: "cppgreet:50051"
    links:
    - cppgreet
